#!/bin/bash
#
# This file was automatically generated by s2e-env at {{ creation_time }}
#
# This script is used to run the S2E analysis. Additional QEMU command line
# arguments can be passed to this script at run time.
#

FIRMWARE="{{ firmware }}"
FUZZ_IN="AFL/{{ firmware }}_fuzz_in"
FUZZ_OUT="AFL/{{ firmware }}_fuzz_out"
SEED_FILE="{{ seed }}"
if [ ! -d $FUZZ_IN ];then
	mkdir -p $FUZZ_IN
	cp -i $SEED_FILE $FUZZ_IN
fi


if [ ! -d $FUZZ_OUT ];then
	mkdir -p $FUZZ_OUT
else
	echo "You need to rm $FUZZ_OUT first"
fi
	afl-fuzz -i $FUZZ_IN -o $FUZZ_OUT -t 100000 uEmu
